---
- name: Creates directory
  file: path="{{ openslides_instance_path }}" state=directory

- name: Creates data directory
  file: path="{{ openslides_instance_path }}/data" state=directory

- set_fact:
    setting_db_template: "settings_db_{{ openslides_instance_db }}.j2"

- name: Create Settings
  template:
    dest: "{{ openslides_instance_path }}/settings.py"
    src: settings.py.j2

- name: Create supervisor configuration
  template:
    dest: "{{ openslides_instance_path }}/supervisord.conf"
    src: supervisord.conf.j2

- name: Create supervisor configuration
  template:
    dest: "{{ openslides_instance_path }}/502.html"
    src: 502.html.j2
