---
- getent: database=passwd

- name: Check variable openslides_secure_key
  when: not openslides_secure_key
  fail:
    msg: The variable openslides_secure_key is not set.

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- set_fact:
    username_on_the_host: "{{username_on_the_host.stdout}}"

- set_fact:
    openslides_uid: "{{ getent_passwd[username_on_the_host][1] }}"
    openslides_gid: "{{ getent_passwd[username_on_the_host][2] }}"

- name: Create nginx configuration
  include: create_nginx_conf.yml

- name: Create instance container
  include: create_container.yml

- name: Create and start systemd units
  include: create_units.yml

- wait_for: path={{ openslides_instance_path }}/rkt-uuid

- pause: seconds=5

# setup manage command
- shell: cat {{ openslides_instance_path }}/rkt-uuid
  register: rkt_uuid
- set_fact:
    openslides_rkt_manage: /usr/bin/rkt enter {{ rkt_uuid.stdout }} /app/manage.py

- name: Initialize database
  include: init_instance_database.yml

- stat: path={{ openslides_instance_path }}/static
  register: static_path

- name: Collect static
  sudo: yes
  sudo_user: root
  when: static_path.stat.exists == False
  command: '{{ openslides_rkt_manage }} collectstatic --noinput'

- name: Change file permissions
  sudo: yes
  sudo_user: root
  file: path={{ openslides_instance_path }} recurse=yes owner={{ username_on_the_host}}

- name: Copy projector logo file
  when: openslides_instance_projector_logo != ""
  copy: src={{ upload_dir }}/{{ openslides_instance_projector_logo }} dest={{ openslides_instance_path }}/static/img/logo-projector.png

- include: recreate_units.yml

- name: mark instance installed
  file: path={{ openslides_instance_path }}/installed state=touch

